version: "3.9"

services:
  admont:
    build: .
    tty: true
    environment:
      DISPLAY: ":0"
      XAUTHORITY: "/tmp/.docker.xauth"
      TZ: "America/New_York"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /home/$USER:/docker
      - ./.env:/app/.env
      - ./data:/app/data
    container_name: admont